Repository robotology/yarp, pull requests merged in 2024-06, with the labels that each got.

#3107 yarpbatterygui now compatible with battery_nwc_yarp
  doc/release/master.md
  src/yarpbatterygui/main.cpp
Labels: Component: GUI - yarpbatterygui, PR Type: Bugfix

#3082 Do not refer anymore to deb binary packages from icub.eu anymore
  doc/001_installation/3_install.dox
  doc/001_installation/3_install_conda.md
  doc/001_installation/3_install_linux.md
Labels: Component: Documentation

#3111 NameServerContainer: do not print "database needs to be reset" message
  src/libYARP_serversql/src/yarp/serversql/impl/NameServerContainer.cpp
Labels: Component: Tool - yarpserver
